_target_: bliss.models.decoder.ImageDecoder
n_bands: 1
slen: 30
tile_slen: 2
ptile_slen: 6
prob_galaxy: 0.0
max_sources: 1
mean_sources: 0.015
min_sources: 0
f_min: 1e5
f_max: 1e6
psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
background_values:
  - 865.0
