name: SleepPhase
image:
  slen: 4
  n_bands: 1
  background:
    - 865.0
galaxy:
  slen: 53
  latent_dim: 8
kwargs:
  decoder_kwargs:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: 4
    ptile_slen: 52
    border_padding: 24
    prob_galaxy: 1.0
    n_galaxy_params: ${model.galaxy.latent_dim}
    max_sources: 1
    mean_sources: 1
    min_sources: 1
    gal_slen: ${model.galaxy.slen}
    autoencoder_ckpt: ${paths.models}/gaussian_ae.ckpt
    latents_file: ${paths.data}/latents_simulated_gaussian_galaxies.pt
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values: ${model.image.background}
  encoder_kwargs:
    n_bands: ${model.image.n_bands}
    tile_slen: ${model.kwargs.decoder_kwargs.tile_slen}
    ptile_slen: 52
    max_detections: ${model.kwargs.decoder_kwargs.max_sources}
  use_galaxy_encoder: True
  annotate_probs: False
