# @package _group_
name: SleepPhase
image:
  slen: 30
  n_bands: 1
  background:
    - 686.0
galaxy:
  slen: 51
  latent_dim: 8
decoder:
  params:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: 2
    ptile_padding: 1
    prob_galaxy: 0.0
    n_galaxy_params: ${model.galaxy.latent_dim}
    max_sources: 2
    mean_sources: 0.015
    min_sources: 0
    f_min: 1e4
    f_max: 1e6
    gal_slen: ${model.galaxy.slen}
    decoder_file:
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values: ${model.image.background}
encoder:
  params:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: ${model.decoder.tile_slen}
    ptile_slen: 8
    max_detections: ${model.decoder.max_sources}
    n_galaxy_params: ${model.galaxy.latent_dim}
    background_pad_value: ${model.image.background.0}
    enc_conv_c: 20
    enc_kern: 3
    enc_hidden: 256
