# @package _group_
name: SleepPhase
image:
  slen: 40
  n_bands: 1
  background:
    - 633.0
galaxy:
  slen: 44
  latent_dim: 8
kwargs:
  decoder_kwargs:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: 4
    ptile_slen: 36
    border_padding: 4
    prob_galaxy: 1.0
    n_galaxy_params: ${model.galaxy.latent_dim}
    max_sources: 1
    mean_sources: 0.015
    min_sources: 0
    gal_slen: ${model.galaxy.slen}
    decoder_file: ${paths.models}/sdss_toy_gaussian_simple.dat
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values: ${model.image.background}
  encoder_kwargs:
    n_bands: ${model.image.n_bands}
    tile_slen: ${model.kwargs.decoder_kwargs.tile_slen}
    ptile_slen: 12
    max_detections: ${model.kwargs.decoder_kwargs.max_sources}
  use_galaxy_encoder: False
