# @package _group_
name: SleepPhase
use_galaxy_encoder: False
image:
  slen: 40
  n_bands: 1
  background:
    - 686.0
galaxy:
  slen: 51
  latent_dim: 8
decoder:
  params:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: ${model.image.slen}
    ptile_slen: ${model.image.slen}
    prob_galaxy: 1.0
    n_galaxy_params: ${model.galaxy.latent_dim}
    max_sources: 1
    mean_sources: 0.85
    min_sources: 0
    gal_slen: ${model.galaxy.slen}
    decoder_file: ${paths.root}/data/galaxy_decoder_1_band.dat
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values: ${model.image.background}
    loc_min: 0.25
    loc_max: 0.75
encoder:
  params:
    n_bands: ${model.image.n_bands}
    tile_slen: ${model.decoder.params.tile_slen}
    ptile_slen: ${model.decoder.params.tile_slen}
    max_detections: ${model.decoder.params.max_sources}
galaxy_encoder:
  params:
    n_bands: 1
    slen:
