# @package _group_
name: SleepPhase
image:
  slen: 40
  n_bands: 1
  background:
    - 633.0
galaxy:
  slen: 41
  latent_dim: 8
decoder:
  params:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: 4
    ptile_slen: 36
    border_padding: 4
    prob_galaxy: 0.5
    n_galaxy_params: ${model.galaxy.latent_dim}
    max_sources: 1
    mean_sources: 0.015
    min_sources: 0
    gal_slen: ${model.galaxy.slen}
    decoder_file: ${paths.root}/data/sdss_gal_decoder_1_band.dat
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values: ${model.image.background}
encoder:
  params:
    n_bands: ${model.image.n_bands}
    tile_slen: ${model.decoder.params.tile_slen}
    ptile_slen: 12
    max_detections: ${model.decoder.params.max_sources}
    channel: 16
    spatial_dropout: 0
    dropout: 0
    hidden: 256
    downsample_with_pool: True
use_galaxy_encoder: False
