outdir: ${paths.output}/sdss_figures
real: false
eval_mean_detections: 0.004
map_n_source_weights:
    - 1.0
    - 9.0
photo_catalog:
    sdss_path: ${paths.sdss}
    run: 94
    camcol: 1
    field: 12
    band: 2
frame:
    _target_: reconstruction.SDSSFrame
    sdss_dir: ${paths.sdss}
    pixel_scale: 0.396
    coadd_file: ${paths.data}/coadd_catalog_94_1_12.fits
scenes:
    sdss_recon0:
        h: 200
        w: 1700
        size: 300
    # sdss_recon1:
    #     h: 1150
    #     w: 1000
    #     size: 300
    # sdss_recon2:
    #     h: 460
    #     w: 742
    #     size: 300
    # sdss_recon3:
    #     h: 1150 #1400
    #     w: 1710
    #     size: 300
    # sdss_recon4_star_galaxy:
    #     h: 557 #1400
    #     w: 408
    #     size: 300
    # sdss_recon_all:
    #     h: 24
    #     w: 24
    #     size: "all"
