# @package _group_
# image and sdss parameters
sdss_kwargs:
  sdss_dir: ${paths.data}/sdss
  run: 3900
  camcol: 6
  fields:
    - 269
  stampsize: 5
  overwrite_fits_cache: False
  overwrite_cache: False
  center_subpixel: True
bands:
  - 2

# i/o parameters
checkpoint: ${paths.root}/models/sdss_sleep_measure_simple_tiny.ckpt
device: "cuda:${gpus.0}"
output_file: "${paths.data}/var_params.pt"

# coverage for tests
testing: False
