_target_: bliss.models.encoder.ImageEncoder
n_bands: 1
tile_slen: ${model.decoder.tile_slen}
ptile_slen: ${model.decoder.ptile_slen}
max_detections: ${model.decoder.max_sources}
channel: 17
spatial_dropout: 0.11399
dropout: 0.013123
hidden: 185
