# @package _group_
num_workers: 0
deterministic: False
plotting: True
n_epochs: 121
trainer:
  profiler: False
  logger: True
  checkpoint_callback: False
  reload_dataloaders_every_epoch: False
  check_val_every_n_epoch: 10
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: "0,"
