defaults:
    - _self_
    - training: sdss_autoencoder
    - override hydra/job_logging: stdout

hydra:
    output_subdir: null
    run:
        dir: .

mode: train

paths:
    root: ${oc.env:BLISS_HOME}
    sdss: ${paths.root}/data/sdss
    data: ${paths.root}/data
    project: ${paths.root}/case_studies/sdss_galaxies
    output: ${paths.project}/output

datasets:
    sdss_galaxies:
        _target_: bliss.datasets.galsim_galaxies.SingleGalsimGalaxies
        prior:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyPrior
            flux_sample: "pareto"
            min_flux: 622.0
            max_flux: 1e6
            alpha: 0.47
            a_sample: "gamma"
            a_concentration: 0.39330758068481686
            a_loc: 0.8371888967872619
            a_scale: 4.432725319432478
            a_bulge_disk_ratio: 2.0
        decoder:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyDecoder
            n_bands: 1
            slen: 53
            pixel_scale: 0.396
            psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
            psf_slen: 25
            psf_gauss_fwhm: null
            sdss_bands:
                - 2
        background:
            _target_: bliss.datasets.background.ConstantBackground
            background:
                - 865.0
        num_workers: 0
        batch_size: 256
        n_batches: 10
        fix_validation_set: True
        valid_n_batches: 5  #200
    simulated:
        _target_: bliss.datasets.simulated.SimulatedDataset
        decoder: ${models.decoder}
        prior: ${models.prior}
        n_tiles_h: 10
        n_tiles_w: 10
        background:
            _target_: bliss.datasets.background.SimulatedSDSSBackground
            sdss_dir: ${paths.sdss}
            run: 94
            camcol: 1
            field: 12
            bands:
                - 2
        n_batches: 50
        batch_size: 32
        generate_device: "cuda:0"
        fix_validation_set: true
        valid_n_batches: 6  #256

# this architecture is based on yolov5l.yaml, see
# https://github.com/ultralytics/yolov5/blob/master/models/yolov5l.yaml
like_yolov5l:
    nc: 2  # number of classes (a hack to get the right output size)
    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple
    anchors:
        - [4, 4]  # P3/8

    backbone: [
        # [from, number, module, args]
        [-1, 1, Conv, [64, 5, 1]],
        [-1, 3, Conv, [64, 1, 1]],
        [-1, 1, Conv, [128, 3, 2]],
        [-1, 1, Conv, [128, 3, 1]],
        [-1, 1, Conv, [256, 3, 2]],
        [-1, 6, C3, [256]],
        [-1, 1, Conv, [512, 3, 2]],
        [-1, 9, C3, [512]],
        [-1, 1, Conv, [1024, 3, 2]],
        [-1, 3, C3, [1024]],
        [-1, 1, SPPF, [1024, 5]],
    ]

    head: [
        [-1, 1, Conv, [512, 1, 1]],
        [-1, 1, nn.Upsample, [None, 2, 'nearest']],
        [[-1, 6], 1, Concat, [1]],
        [-1, 3, C3, [512, false]],

        [-1, 1, Conv, [256, 1, 1]],
        [-1, 1, nn.Upsample, [None, 2, 'nearest']],
        [[-1, 4, 5], 1, Concat, [1]],
        [-1, 3, C3, [256, false]],

        [[17], 1, Detect, [nc, anchors]],
    ]

models:
    binary:
        _target_: bliss.models.binary.BinaryEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        channel: 8
        hidden: 128
        spatial_dropout: 0.0
        dropout: 0.0
        optimizer_params:
            lr: 1e-4
    decoder:
        _target_: bliss.models.decoder.ImageDecoder
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        border_padding: 24
        psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
        galaxy_model:
            _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
            slen: ${models.galaxy_net.slen}
            latent_dim: ${models.galaxy_net.latent_dim}
            hidden: ${models.galaxy_net.hidden}
            n_bands: ${models.galaxy_net.n_bands}
            ckpt: ${paths.project}/models/sdss_autoencoder.pt
        psf_slen: 25
        sdss_bands:
            - 2
    detection_encoder:
        _target_: bliss.models.detection_encoder.DetectionEncoder
        n_bands: ${models.decoder.n_bands}
        tile_slen: ${models.decoder.tile_slen}
        ptile_slen: 52
        annotate_probs: True
        slack: 1.0
        optimizer_params:
            lr: 1e-3
        scheduler_params:
            milestones: [32]
            gamma: 0.1
        architecture: ${like_yolov5l}
    galaxy_encoder:
        _target_: bliss.models.galaxy_encoder.GalaxyEncoder
        decoder: ${models.decoder}
        autoencoder: ${models.galaxy_net}
        hidden: ${models.galaxy_net.hidden}
        optimizer_params:
            lr: 1e-4
    galaxy_net:
        _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
        slen: 53
        latent_dim: 8
        hidden: 256
        n_bands: 1
        optimizer_params:
            lr: 1e-3
    prior:
        _target_: bliss.models.prior.ImagePrior
        n_bands: 1
        max_sources: 1
        mean_sources: 0.03
        min_sources: 0
        f_min: 622.0
        f_max: 1e6
        alpha: 0.43
        prob_galaxy: 0.7
        galaxy_prior:
            _target_: bliss.models.prior.GalaxyPrior
            n_latent_batches: 160
            autoencoder: ${models.galaxy_net}
            autoencoder_ckpt: ${paths.project}/models/sdss_autoencoder.pt
            latents_file: ${paths.project}/models/latents_simulated_sdss_galaxies.pt
            galaxy_dataset: ${datasets.sdss_galaxies}

training:
    n_epochs: 121
    experiment: default
    version: null
    save_top_k: 1
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: True
        enable_checkpointing: False
        profiler: null
        reload_dataloaders_every_n_epochs: 0
        max_epochs: ${training.n_epochs}
        min_epochs: ${training.n_epochs}
        accelerator: "gpu"
        devices: 1
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        check_val_every_n_epoch: 10
        log_every_n_steps: 10 # correspond to n_batches
    testing:
        file: null
        batch_size: 32
        num_workers: 0
    weight_save_path: ${paths.project}/models/${training.name}.pt
    seed: 42

plots:
    figs:
        - "sdss_detection"
        - "sdss_recon"
    location_checkpoint: ${paths.project}/models/sdss_detection_encoder.pt
    galaxy_checkpoint: ${paths.project}/models/sdss_galaxy_encoder.pt
    binary_checkpoint: ${paths.project}/models/sdss_binary.pt
    cachedir: ${paths.project}/output/sdss_figures_cache
    figdir: ${paths.project}/figures
    image_format: "png"
    overwrite: false
    psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
    sdss_pixel_scale: 0.396
    device: "cuda:0"
    coadd_file: ${paths.sdss}/coadd_catalog_94_1_12.fits
    photo_catalog:
        sdss_path: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        band: 2
    frame:
        _target_: bliss.inference.SDSSFrame
        sdss_dir: ${paths.sdss}
        pixel_scale: 0.396
        cat_file: ${plots.coadd_file}
        cat_type: "coadd"
    encoder:
        n_images_per_batch: 10
        n_rows_per_batch: 15
    scenes:
        sdss_recon0:
            h: 198
            w: 1700
            size: 300
        sdss_recon1:
            h: 1154
            w: 997
            size: 300
        sdss_gal_blend1:
            h: 460
            w: 744
            size: 32
            ra: 336.6350
            dec: -0.9611
            comment: "Mild blend with two medium-sized galaxies of comparable size. In DECals, they appear to be well separated elliptical monochromatic galaxies with no striking features."
        sdss_gal_blend2:
            h: 1404
            w: 1718
            size: 32
            ra: 336.7383
            dec: -0.8536
            comment: "Relatively mild blend with two small-sized galxies of comparable size. In DECals, they appear to have slightly different color but each galaxy is monochromatic. One important note is that they are surrounded by two saturated objects on each side (one outside the frame but diffraction spike is visible, other one masked out)."
        sdss_gal_blend3:
            h: 212
            w: 280
            size: 32
            ra: 336.6068
            dec: -1.0110
            comment: "Drastic blend in frame that by eye could easily be mistaken as one object. The objects are relatively faint (~20 mag) and small. In DECals it looks like a more severe blend than the previous one, but each galaxy has a different color and its clearly noticeable here. Galaxies are elliptical with no significant features. BLISS should predict >5% for second object in blend."
        sdss_gal_blend4:
            h: 1252
            w: 240
            size: 32
            ra: 336.7208
            dec: -1.0159
            comment: "In the frame it looks like a very mild blend, with one small bright galaxy and a larger relatively bright galaxy. In DECals we see that the larger galaxy has spiral arms features and one of the arms is blended with the smaller galaxy. This model misfit might be problematic for BLISS. Both galaxies have different colors."
        sdss_gal_blend5:
            h: 460
            w: 506
            size: 48
            ra: 336.6349
            dec: -0.9858
            comment: "This three-way blend with 2 galaxies and a star is complicated. In DECals it appears that there are actually more like 7 objects with different colors that are blended so this is a very complicated case for BLISS to handle. The undetectable objects make it look like the detectable are nothing that our model could generate. If we want to get this one right, we'd need to have our model generate faint/undetectable objects too, so that the encoder is robust to this type of variation. Increasing the number of detections per tile from 1 to 2 might also be necessary."
