# @package _global_
training:
  name: "sdss_detection_encoder"
  model: ${models.detection_encoder}
  dataset: ${datasets.galsim_blended_galaxies_rand}
  optimizer_params:
    lr: 1e-4
  n_epochs: 1001
  save_top_k: 10
  trainer:
    enable_checkpointing: True
