defaults:
    - _self_
    - training: sdss_vae
    - override hydra/job_logging: stdout

# completely disable hydra logging
# https://github.com/facebookresearch/hydra/issues/910
hydra:
    output_subdir: null
    run:
        dir: .

mode: train

gpus: 1 # use a single gpu by default.

paths:
    root: ${oc.env:BLISS_HOME}
    sdss: ${paths.root}/data/sdss
    data: ${paths.root}/data
    project: ${paths.root}/case_studies/sdss_galaxies_vae
    output: ${paths.project}/output

datasets:
    sdss_blended_galaxies:
        _target_: bliss.datasets.sdss_blended_galaxies.SdssBlendedGalaxies
        sleep: ${models.sleep}
        binary_encoder: ${models.binary}
        sleep_ckpt: ${paths.project}/models/sdss_sleep.pt
        binary_ckpt: ${paths.project}/models/sdss_binary.pt
        sdss_dir: ${paths.sdss}
        prerender_device: "cuda"
        stride_factor: 0.25
    sdss_galaxies:
        _target_: bliss.datasets.galsim_galaxies.SDSSGalaxies
        num_workers: 5
        batch_size: 64
        n_batches: 10
        background: 865
        slen: 53
        min_flux: 1e3
        max_flux: 3.5e5
        min_a_d: 0.8
        max_a_d: 6.5
        min_a_b: 0.8
        max_a_b: 3.6 # from catalog with mag < 22.2 cut.
        flux_sample: "uniform"
        psf_image_file: ${paths.data}/psField-000094-1-0012-PSF-image.npy
    simulated:
        _target_: bliss.datasets.simulated.SimulatedDataset
        decoder: ${models.decoder}
        prior: ${models.prior}
        background:
            _target_: bliss.datasets.simulated.SimulatedSDSSBackground
            sdss_dir: ${paths.sdss}
            run: 94
            camcol: 1
            field: 12
            bands:
                - 2
        n_tiles_h: 10
        n_tiles_w: 10
        n_batches: 10
        batch_size: 32
        generate_device: "cuda:0"
        testing_file: null
    toy_gaussian:
        _target_: bliss.datasets.galsim_galaxies.ToyGaussian
        num_workers: 0
        n_batches: 10
        batch_size: 64
        slen: 53
        background: 865.
        psf_fwhm: 0.8
        pixel_scale: 0.4
        min_flux: 300 # to be observable it cannot be too below background.
        max_flux: 10000
        min_hlr: 0.8
        max_hlr: 3.0
        max_e: 0.6

models:
    binary:
        _target_: bliss.models.binary.BinaryEncoder
        input_transform:
            _target_: bliss.models.location_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        channel: 8
        hidden: 128
        spatial_dropout: 0.0
        dropout: 0.0
    decoder:
        _target_: bliss.models.decoder.ImageDecoder
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        border_padding: 24
        psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
        galaxy_ae: ${models.galaxy_vae}
        galaxy_ae_ckpt: ${paths.project}/models/sdss_vae.pt
        sdss_bands:
            - 2
    encoder:
        _target_: bliss.models.location_encoder.LocationEncoder
        input_transform:
            _target_: bliss.models.location_encoder.ConcatBackgroundTransform
        n_bands: ${models.decoder.n_bands}
        tile_slen: ${models.decoder.tile_slen}
        ptile_slen: 52
        max_detections: ${models.prior.max_sources}
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
        hidden: 128
    galaxy_encoder:
        _target_: bliss.models.galaxy_encoder.GalaxyEncoder
        decoder: ${models.decoder}
        autoencoder: ${models.galaxy_vae}
        hidden: ${models.galaxy_vae.hidden}
        #vae_flow: ${models.galaxy_flow}
        #vae_flow_ckpt: ${paths.project}/models/sdss_vae_flow.pt
    galaxy_flow:
        _target_: bliss.models.vae.galaxy_flow.CenteredGalaxyLatentFlow
        vae: ${models.galaxy_vae}
        vae_ckpt: ${paths.project}/models/sdss_vae.pt
    galaxy_vae:
        _target_: bliss.models.vae.galaxy_vae.OneCenteredGalaxyVAE
        slen: 53
        latent_dim: 32
        hidden: 256
        n_bands: 1
    prior:
        _target_: bliss.models.prior.ImagePrior
        n_bands: 1
        max_sources: 1
        mean_sources: 0.03
        min_sources: 0
        f_min: 1e3
        f_max: 1e6
        alpha: 0.5
        prob_galaxy: 0.7
        galaxy_prior:
            _target_: bliss.models.vae.prior.GalaxyVAEPrior
            latent_dim: ${models.galaxy_vae.latent_dim}
            #vae_flow: ${models.galaxy_flow}
            #vae_flow_ckpt: ${paths.project}/models/sdss_vae_flow.pt
    sleep:
        _target_: bliss.sleep.SleepPhase
        encoder: ${models.encoder}
        decoder: ${models.decoder}
        annotate_probs: True

generate:
    dataset:
    file:
    common: # What attributes of dataset items are in common and should not be stacked?
    n_plots: 25
predict:
    sdss:
        _target_: bliss.datasets.sdss.SloanDigitalSkySurvey
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        fields:
            - 12
    bands:
        - 2

    # chunk properties
    clen: 300

    # i/o parameters
    sleep_checkpoint: ${paths.project}/models/sdss_sleep.pt
    galaxy_checkpoint: ${paths.project}/models/sdss_galaxy_encoder.pt
    galaxy_checkpoint_real: ${paths.project}/models/sdss_galaxy_encoder_real.pt
    binary_checkpoint: ${paths.project}/models/sdss_binary.pt
    device: "cuda:0"
    output_file: null

    # coverage for tests
    testing: False

training:
    n_epochs: 121
    experiment: default
    version: null
    save_top_k: 1
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: True
        enable_checkpointing: False
        profiler: null
        reload_dataloaders_every_epoch: False
        max_epochs: ${training.n_epochs}
        min_epochs: ${training.n_epochs}
        gpus: ${gpus}
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        check_val_every_n_epoch: 10
        log_every_n_steps: 10 # correspond to n_batches
        deterministic: False
    testing:
        file: null
        batch_size: 32
        num_workers: 0
    weight_save_path: ${paths.project}/models/${training.name}.pt

reconstruct:
    device: "cuda:0"
    psf_file: ${paths.data}/psField-000094-1-0012-PSF-image.npy
    real: False
    slen: 300
    generated_frame: False
    outdir:
    scenes:
        # sdss_recon0:
        #     h: 200
        #     w: 1700
        #     size: 300
        # sdss_recon1:
        #     h: 1150
        #     w: 1000
        #     size: 300
