defaults:
    - _self_
    - training: binary
    - override hydra/job_logging: stdout

# completely disable hydra logging
# https://github.com/facebookresearch/hydra/issues/910
hydra:
    output_subdir: null
    run:
        dir: .

mode: train

gpus: 6 # use a single gpu by default.

paths:
    root: ${oc.env:BLISS_HOME}
    sdss: ${paths.root}/data/sdss
    data: ${paths.root}/data
    project: ${paths.root}/case_studies/strong_lensing
    output: ${paths.project}/output

datasets:
    sdss_blended_galaxies:
        _target_: bliss.datasets.sdss_blended_galaxies.SdssBlendedGalaxies
        detection_encoder: ${models.detection_encoder}
        binary_encoder: ${models.binary}
        location_ckpt: ${paths.project}/models/detection_encoder.pt
        binary_ckpt: ${paths.project}/models/binary.pt
        sdss_dir: ${paths.sdss}
        prerender_device: "cuda"
    sdss_galaxies:
        _target_: bliss.datasets.galsim_galaxies.SingleGalsimGalaxies
        prior:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyPrior
            flux_sample: "pareto"
            min_flux: 622.0
            max_flux: 1e6
            alpha: 0.47
            a_sample: "gamma"
            a_concentration: 0.39330758068481686
            a_loc: 0.8371888967872619
            a_scale: 4.432725319432478
            a_bulge_disk_ratio: 2.0
        decoder:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyDecoder
            n_bands: 1
            slen: 53
            pixel_scale: 0.396
            psf_image_file: ${paths.data}/sdss/5313/3/117/psField-005313-3-0117.fits
        background:
            _target_: bliss.datasets.background.ConstantBackground
            background:
                - 865.0
        num_workers: 0
        batch_size: 64
        n_batches: 10
    galsim_blended_galaxies:
        _target_: bliss.datasets.galsim_galaxies.GalsimBlend
        prior: ${datasets.sdss_galaxies.prior}
        decoder:
            _target_: bliss.models.galsim_decoder.FullCatalogDecoder
            single_galaxy_decoder: ${datasets.sdss_galaxies.decoder}
            slen: 40
            bp: 24
        background: ${datasets.sdss_galaxies.background}
        num_workers: 0
        batch_size: 64
        n_batches: 10
        max_shift: 10
        max_n_sources: 3
    simulated:
        _target_: bliss.datasets.simulated.SimulatedDataset
        decoder: ${models.decoder}
        prior: ${models.prior}
        n_tiles_h: 10
        n_tiles_w: 10
        background:
            _target_: bliss.datasets.background.SimulatedSDSSBackground
            sdss_dir: ${paths.sdss}
            run: 94
            camcol: 1
            field: 12
            bands:
                - 2
        n_batches: 10
        batch_size: 32
        generate_device: "cuda:0"
        testing_file: null
    toy_gaussian:
        _target_: bliss.datasets.galsim_galaxies.ToyGaussian
        num_workers: 0
        n_batches: 10
        batch_size: 64
        slen: 53
        n_bands: 1
        background: 865.
        psf_fwhm: 0.8
        pixel_scale: 0.4
        min_flux: 300
        max_flux: 10000
        min_hlr: 0.8
        max_hlr: 3.0
        max_e: 0.6

models:
    lensing_binary:
        _target_: bliss.models.lensing_binary_encoder.LensingBinaryEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        channel: 8
        hidden: 128
        spatial_dropout: 0.0
        dropout: 0.0
    binary:
        _target_: bliss.models.binary.BinaryEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        channel: 8
        hidden: 128
        spatial_dropout: 0.0
        dropout: 0.0
    decoder:
        _target_: bliss.models.decoder.ImageDecoder
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        border_padding: 24
        psf_params_file: ${paths.data}/sdss/5313/3/117/psField-005313-3-0117.fits
        galaxy_model:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyDecoder
            n_bands: 1
            slen: 53
            pixel_scale: 0.396
            psf_params_file: ${paths.data}/sdss/5313/3/117/psField-005313-3-0117.fits
            psf_slen: 25
            sdss_bands:
                - 2
        psf_slen: 25
        sdss_bands:
            - 2
    detection_encoder:
        _target_: bliss.models.detection_encoder.DetectionEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: ${models.decoder.n_bands}
        tile_slen: ${models.decoder.tile_slen}
        ptile_slen: 52
        mean_detections: ${models.prior.mean_sources}
        max_detections: ${models.prior.max_sources}
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
        hidden: 128
        annotate_probs: True
        slack: 1.0
    galaxy_encoder:
        _target_: bliss.models.galsim_encoder.GalsimEncoder
        n_bands: ${models.decoder.n_bands}
        tile_slen: ${models.decoder.tile_slen}
        ptile_slen: 52
        hidden: 128
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
    lens_encoder:
        _target_: bliss.models.lens_encoder.LensEncoder
        n_bands: ${models.decoder.n_bands}
        tile_slen: ${models.decoder.tile_slen}
        ptile_slen: 52
        hidden: 128
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
    galaxy_net:
        _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
        slen: 53
        latent_dim: 8
        hidden: 256
        n_bands: 1
    prior:
        _target_: bliss.models.prior.ImagePrior
        n_bands: 1
        max_sources: 1
        mean_sources: 0.03
        min_sources: 0
        f_min: 1e3
        f_max: 1e6
        alpha: 0.5
        prob_galaxy: 0.7
        prob_lensed_galaxy: 0.2
        galaxy_prior:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyPrior
            flux_sample: "pareto"
            min_flux: 622.0
            max_flux: 1e6
            alpha: 0.47
            a_sample: "gamma"
            a_concentration: 0.39330758068481686
            a_loc: 0.8371888967872619
            a_scale: 4.432725319432478
            a_bulge_disk_ratio: 2.0
        lensed_galaxy_prior:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyPrior
            flux_sample: "pareto"
            min_flux: 622.0
            max_flux: 1e4
            alpha: 0.47
            a_sample: "gamma"
            a_concentration: 0.39330758068481686
            a_loc: 0.8371888967872619
            a_scale: 4.432725319432478
            a_bulge_disk_ratio: 2.0

generate:
    dataset:
    file:
    n_plots:

predict:
    sdss:
        _target_: bliss.datasets.sdss.SloanDigitalSkySurvey
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        fields:
            - 12
    bands:
        - 2

    # chunk properties
    clen: 300

    # i/o parameters
    location_checkpoint: ${paths.project}/models/detection_encoder.pt
    galaxy_checkpoint: ${paths.project}/models/galaxy_encoder.pt
    binary_checkpoint: ${paths.project}/models/binary.pt
    device: "cuda:0"
    output_file: null

    # coverage for tests
    testing: False

training:
    n_epochs: 121
    experiment: default
    version: null
    save_top_k: 1
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: True
        enable_checkpointing: False
        profiler: null
        reload_dataloaders_every_n_epochs: 0
        max_epochs: ${training.n_epochs}
        min_epochs: ${training.n_epochs}
        gpus: ${gpus}
        strategy: "ddp_find_unused_parameters_false"
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        check_val_every_n_epoch: 10
        log_every_n_steps: 10 # correspond to n_batches
    testing:
        file: null
        batch_size: 32
        num_workers: 0
    weight_save_path: ${paths.project}/models/${training.name}.pt
    seed: 42

plots:
    location_checkpoint: ${paths.project}/models/detection_encoder.pt
    galaxy_checkpoint: ${paths.project}/models/galaxy_encoder.pt
    binary_checkpoint: ${paths.project}/models/binary.pt
    lensing_binary_checkpoint: ${paths.project}/models/lensing_binary_encoder.pt
    lens_checkpoint: ${paths.project}/models/lens_encoder.pt
    figs:
        - 1
        - 2
        - 3
    cachedir: ${paths.project}/output/sdss_figures_cache
    figdir: ${paths.project}/figures
    image_format: "png"
    overwrite: false
    simulated_sdss_individual_galaxies: ${paths.project}/models/simulated_sdss_individual_galaxies.pt
    simulated_blended_galaxies: ${paths.project}/models/simulated_blended_galaxies.pt
    sdss_pixel_scale: 0.396
    device: "cuda:0"
    coadd_file: ${paths.sdss}/coadd_catalog_94_1_12.fits
    psf_file: ${paths.data}/sdss/5313/3/117/psField-005313-3-0117.fits
    photo_catalog:
        sdss_path: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        band: 2
    frame:
        _target_: bliss.inference.SDSSFrame
        sdss_dir: ${paths.sdss}
        pixel_scale: 0.396
        coadd_file: ${plots.coadd_file}
    encoder:
        n_images_per_batch: 10
        n_rows_per_batch: 15
    scenes:
        sdss_recon0:
            h: 200
            w: 1700
            size: 300
        sdss_recon1:
            h: 1152
            w: 1000
            size: 300
        sdss_gal_blend1:
            h: 460
            w: 744
            size: 32
            ra: 336.6350
            dec: -0.9611
            comment: "Mild blend with two medium-sized galaxies of comparable size. In DECals, they appear to be well separated elliptical monochromatic galaxies with no striking features."
        sdss_gal_blend2:
            h: 1404
            w: 1720
            size: 32
            ra: 336.7383
            dec: -0.8536
            comment: "Relatively mild blend with two small-sized galxies of comparable size. In DECals, they appear to have slightly different color but each galaxy is monochromatic. One important note is that they are surrounded by two saturated objects on each side (one outside the frame but diffraction spike is visible, other one masked out)."
        sdss_gal_blend3:
            h: 212
            w: 280
            size: 32
            ra: 336.6068
            dec: -1.0110
            comment: "Drastic blend in frame that by eye could easily be mistaken as one object. The objects are relatively faint (~20 mag) and small. In DECals it looks like a more severe blend than the previous one, but each galaxy has a different color and its clearly noticeable here. Galaxies are elliptical with no significant features. BLISS should predict >5% for second object in blend."
        sdss_gal_blend4:
            h: 1252
            w: 240
            size: 32
            ra: 336.7208
            dec: -1.0159
            comment: "In the frame it looks like a very mild blend, with one small bright galaxy and a larger relatively bright galaxy. In DECals we see that the larger galaxy has spiral arms features and one of the arms is blended with the smaller galaxy. This model misfit might be problematic for BLISS. Both galaxies have different colors."
        sdss_gal_blend5:
            h: 460
            w: 508
            size: 48
            ra: 336.6349
            dec: -0.9858
            comment: "This three-way blend with 2 galaxies and a star is complicated. In DECals it appears that there are actually more like 7 objects with different colors that are blended so this is a very complicated case for BLISS to handle. The undetectable objects make it look like the detectable are nothing that our model could generate. If we want to get this one right, we'd need to have our model generate faint/undetectable objects too, so that the encoder is robust to this type of variation. Increasing the number of detections per tile from 1 to 2 might also be necessary."
