# @package _group_
search_space:
  enc_conv_c:
    - 8
    - 33
  enc_kern:
    - 3
    - 4
  enc_hidden:
    - 64
    - 321
  lr:
    - 1e-7
    - 1e-3
  weight_decay:
    - 1e-6
    - 1e-2
n_epochs: 200
gpus_per_trial: 1
allocated_gpus: 4
max_concurrent: 4
grace_period: 10
n_samples: 20
verbose: 1
seed: 42
save: True
limit_val_batches: 1
best_config_save_path: ${paths.root}/config/tuning/m2_best_result.yml
log_path: ${paths.root}/temp/tuning
